<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>D&eacute;tection automatique des param&egrave;tres...</title>
<link rel="Home page" href="http://www.telessonne.fr/pages.php" title="Accueil" />
<meta http-equiv="Content-Script-Type" content="text/javascript">
<meta http-equiv="Content-Style-Type" content="text/ccs">
<link href="style5.css" rel="stylesheet" type="text/css">
<script language="JavaScript" type="text/JavaScript">
<!--
//function stopError() { return true; }
//window.onerror = stopError;
-->
</script>
<script language="JavaScript" type="text/JavaScript">
<!--
if (document.all) { window.resizeTo('720','560'); }
else if (document.layers) { window.outerHeight = 720; window.outerWidth = 560; }
var left = (screen.availWidth-720)/2; var top = (screen.availHeight-560)/2;
window.moveTo(left,top);
-->
</script><script src="cookies.js"></script><script language="JavaScript" type="text/JavaScript">
<!--  Script Mix By Molokoloco (^_^) 2003
// ON PASSE SI DEJA COOKIES
//CookieWrite("Player", "PlayerWmp", 100);

var Pref = '<?php echo $Pref; ?>';
var CDebit = GetCookie('Debit');
var CPlayer = GetCookie('Player');
var videosId ='<?php echo $videosId; ?>';
var emissionId ='<?php echo $emissionId; ?>';

if (Pref=='') {
	if ((CDebit=='Haut')&&(CPlayer=='PlayerReal'||CPlayer=='PlayerWmp')) {
	//if (CDebit=='Haut' && CPlayer=='PlayerReal') {
	self.location.href="videos_player.php?emissionId="+emissionId+"&videosId="+videosId+"&FDebit=Haut";
	}
}
//alert(CPlayer+CDebit);
-->
</script>
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</script>
</head>
<body scroll="auto" onLoad="focus();hideLoadingPage();MM_preloadImages('images_videos/images/aide-close-on_01.png','images_videos/images/aide-close-on_02.png')">
<div id="overDiv" style="Z-INDEX: 10; POSITION: absolute"></div>
<script language="JavaScript">var offsetx = 10; var offsety = 20;</script> 
<script language="JavaScript" src="bulle.js"></script>
<script src="testplugins.js"></script><script language="JavaScript">
<!--
if (pluginlist.indexOf("RealPlayer")!=-1) { PlayerReal = "oui"; }
else { PlayerReal = "non"; }
if (pluginlist.indexOf("Windows Media Player")!=-1) { PlayerWmp = "oui"; }
else { PlayerWmp = "non"; }
CookieWrite("PlayerReal", PlayerReal, 1);
CookieWrite("PlayerWmp", PlayerWmp, 1);
// CookieWrite("Player", "PlayerReal", 1);
-->
</script><script language="Javascript">
<!--	
if (CDebit != 'Haut' || CDebit != 'Bas' ) {
var time = new Date();
var starttime = time.getTime();
var Ko = "aavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhg ecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgsskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfcjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskshgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhgkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnlfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecvbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjlfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxaavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecvbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdxgcnjhgkdkjgujhdgsbfjrgvsnkfgskskhgecavbjfjhbfckjnfrklfgckgfjrhglkjcnlvsdgdsfgdx";
var time = new Date();
var endtime = time.getTime();
if (endtime == starttime) downloadtime = 0;
else downloadtime = (endtime-starttime)/1000;
var kbits_of_data = 29696*8/1024*1.2; // data file size
var kbps = (Math.round(kbits_of_data /downloadtime))/10;
if (kbps=="Infinity") { kbps=500; }
if (kbps<60) { var Debit="Bas"; }
else { var Debit="Haut"; }
CookieWrite("Debit", Debit, 10);
}
-->
</script>
<table width="100%" height="100%"  border="0" cellpadding="0" cellspacing="0">
      <tr> 
    <td  align="center"><table width="100%" border="0" cellspacing="0" cellpadding="0">
        <form name="form" action="videos_player_new.php" method="post" enctype="multipart/form-data">
          <tr> 
            <td align="center">
<script language="JavaScript">
<!--
if (Debit == "Bas") {
document.write('<table width="460" border="0" cellpadding="0" cellspacing="0" class="borNoircote">');
document.write('<tr >');
document.write('<td  height="30" align="center" background="images_videos/barre_silver_full.png" class="TdBdB3"><table width="100%" border="0" cellspacing="0" cellpadding="0">');
document.write('<tr>');
document.write('<td align="center"><b><span class="menu"><img src="images/pix.gif" width="28" height="10">');
document.write('BAS D&Eacute;BIT D&Eacute;TECT&Eacute; : HAUT D&Eacute;BIT N&Eacute;CESSAIRE !');
document.write('</span></b></td>');
document.write('<td width="1"><img src="images/pix.gif" width="5" height="5"></td>');
document.write('</tr>');
document.write('</table></td>');
document.write('</tr>');
document.write('<tr > ');
document.write('<td background="images_videos/fdx_mot.gif"><table width="100%" border="0" cellpadding="0" cellspacing="0" class="textpetit2">');
document.write('<tr> ');
document.write('<td width="1" height="50"><img src="images/pix.gif" width="10" height="10"></td>');
document.write('<td width="100%" nowrap class="textpetitdescr" ><table width="100%" border="0" cellpadding="0" cellspacing="0">');
//
document.write('<tr> ');
document.write('<td align="center" height="50"><span class="textpetit2">Connexion &quot;Haut-d&eacute;bit&quot; <b>n&eacute;cessaire</b> pour profiter de nos &eacute;missions en ligne.<br><br>Il y aura beaucoup de coupure dans la diffusion, si vous tentez, néanmoins, de visionner nos vidéos...</span></td>');
document.write('</tr>');
//
document.write('</table></td>');
document.write('</tr>');
document.write('</table></td>');
document.write('</tr>');
document.write('</table>&nbsp;<br>');
}
-->
</script>
<script language="JavaScript">
<!--
if (PlayerReal!="oui" && PlayerWmp!="oui") {
document.write('<table width="460" border="0" cellpadding="0" cellspacing="0" class="borNoircote">');
document.write('<tr >');
document.write('<td  height="30" align="center" background="images_videos/barre_silver_full.png" class="TdBdB3"><table width="100%" border="0" cellspacing="0" cellpadding="0">');
document.write('<tr>');
document.write('<td align="center"><b><span class="menu"><img src="images/pix.gif" width="28" height="10">');
document.write('AUCUN LECTEUR VIDEO D&Eacute;TECT&Eacute; !!!');
document.write('</span></b></td>');
document.write('<td width="1" valign="top"><img src="images_videos/images/aide-close_02.png" name="Image50" width="23" height="30" border="0" id="Image222" onClick="window.open(\'pop_aide-video.php\',\'\',\'status=yes,scrollbars=yes,resizable=yes,width=600,height=400\');" onMouseOver="Bulle(\'Aide sur les Player de vid&eacute;os\');MM_swapImage(\'Image50\',\'\',\'images_videos/images/aide-close-on_02.png\',1)" onMouseOut="nd();MM_swapImgRestore()" style="cursor:hand;"></td>');
document.write('<td width="1"><img src="images/pix.gif" width="5" height="5"></td>');
document.write('</tr>');
document.write('</table></td>');
document.write('</tr>');
//
document.write('<tr>');
document.write('<td colspan="2" align="center" height="50" background="images_videos/fdx_mot.gif"><span class="textpetit2">"<strong>Real Player</strong>" et "<strong>Windows Media Player</strong>" ne sont pas installés :<br><a href="javascript:void()" onClick="window.open(\'pop_aide-video.php\',\'\',\'status=yes,scrollbars=yes,resizable=yes,width=600,height=400\');"><b>en savoir plus</b></a>. Une fois l\'installation terminée, relancez la détection des paramètres en <a href="videos.php?videosId=<?php echo $videosId; ?>&emissionId=<?php echo $emissionId; ?>&Pref=<?php echo $Pref; ?>" >cliquant ici</a>.</span></td>');
document.write('</tr>');
//
document.write('<tr>');
document.write('<td background="images_videos/motif_bar_argent-1b.gif"><table width="100%" border="0" cellpadding="0" cellspacing="0" class="textpetit2">');
document.write('<tr> ');
document.write('<td width="1" height="50"><img src="images/pix.gif" width="10" height="10"></td>');
document.write('<td width="100%" nowrap class="textpetitdescr" ><table width="100%" border="0" cellpadding="0" cellspacing="0">');
//
document.write('<tr>');
document.write('<td width="1%" align="center"><a href="http://www.microsoft.com/windows/windowsmedia/download/default.asp?DispLang=fr" target="_blank" onMouseOver="Bulle(\'Télécharger le lecteur &quot;<b>Windows Media Player</b> série 9&quot; (Gratuit, 10Mo)\');" onMouseOut="nd();"><img src="images_videos/wmp3b.gif" width="82" height="50" border="0"></a></td>');
document.write('<td nowrap class="textpetit2" align="center" ><b>T&eacute;l&eacute;chargez le lecteur &quot;<a href="http://www.microsoft.com/windows/windowsmedia/download/default.asp?DispLang=fr" target="_blank" onMouseOver="Bulle(\'Télécharger le lecteur &quot;<b>Windows Media Player</b> série 9&quot; (Gratuit, 10Mo)\');" onMouseOut="nd();">Windows Media Player</a>&quot;</b></td>');
document.write('</tr>');
//
document.write('<tr>');
document.write('<td width="1%" align="center"><a href="http://forms.real.com/netzip/intl/intl_getrde601.html?lang=fr&h=207.188.7.150&f=windows/mrkt/RIR09D/RealOnePlayerV2GOLD_fr.exe&p=RealOne%2BPlayer&oem=rd_fr&src=030324_intl_radiopasschoice_fr_fr,030324radiopass_choice_dl&tagtype=ie&type=rd_fr" target="_blank" onMouseOver="Bulle(\'Télécharger le lecteur &quot;<b>Real One Player</b>&quot; (Version gratuite ou payante, 8Mo)\');" onMouseOut="nd();"><img src="images_videos/real3b.gif" width="82" height="50" border="0"></a></td>');
document.write('<td nowrap class="textpetit2" align="center" ><b>Ou, t&eacute;l&eacute;chargez le lecteur &quot;<a href="http://forms.real.com/netzip/intl/intl_getrde601.html?lang=fr&h=207.188.7.150&f=windows/mrkt/RIR09D/RealOnePlayerV2GOLD_fr.exe&p=RealOne%2BPlayer&oem=rd_fr&src=030324_intl_radiopasschoice_fr_fr,030324radiopass_choice_dl&tagtype=ie&type=rd_fr" target="_blank" onMouseOver="Bulle(\'Télécharger le lecteur &quot;<b>Real One Player</b>&quot; (Version gratuite ou payante, 8Mo)\');" onMouseOut="nd();">Real One Player</a>&quot;</b></td>');
document.write('</tr>');
//
document.write('</table></td>');
document.write('</tr>');
document.write('</table></td>');
document.write('</tr>');
document.write('</table>&nbsp;<br>');
}
-->
</script>
<table width="460" border="0" cellpadding="0" cellspacing="0" class="borNoircote">
                <tr > 
                  <td  height="30" align="center" background="images_videos/barre_silver_full.png" class="TdBdB3"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                      <tr> 
                        <td align="center"><b><span class="menu"><img src="images/pix.gif" width="28" height="10">CHOIX DE VOTRE LECTEUR VID&Eacute;O</span></b></td>
                        <td width="1"><img src="images_videos/images/aide-close_02.png" name="Image50" width="23" height="30" border="0" id="Image222" onClick="window.open('pop_aide-video.php','','status=yes,scrollbars=yes,resizable=yes,width=600,height=400');" onMouseOver="MM_swapImage('Image222','','images_videos/images/aide-close-on_02.png',1);" title="Aide sur les Player de vidéos" onMouseOut="MM_swapImgRestore();" style="cursor:hand;"></td>
                        <td width="1"><img src="images/pix.gif" width="5" height="5"></td>
                      </tr>
                    </table></td>
                </tr>
                <tr > 
                  <td background="images_videos/motif_bar_argent-1b.gif"><table width="100%" border="0" cellpadding="0" cellspacing="0" class="textpetit2">
                      <tr> 
                        <td width="1" rowspan="2"><img src="images/pix.gif" width="10" height="10"></td>
                        <td width="1" height="26"><script language="JavaScript">
<!--
if (PlayerReal=="oui" && (CPlayer=="PlayerReal" || PlayerWmp!="oui")) {
document.write("<input type='radio' name='FPlayer' value='PlayerReal' checked>");
}
else if (PlayerReal=="oui" && (CPlayer=="PlayerWmp" || PlayerWmp=="oui")) {
document.write("<input type='radio' name='FPlayer' value='PlayerReal'>");
}
else {
document.write("<input type='radio' name='FPlayer' value='PlayerReal' disabled>");
}
-->
</script></td>
                        <td nowrap class="textpetit2"><b>Real One Player</b></td>
                        <td width="1" rowspan="2" ><img src="images_videos/verticale.gif" width="5" height="50"></td>
                        <td width="180" rowspan="2" nowrap class="textpetitdescr" ><table width="100%" border="0" cellpadding="0" cellspacing="0">
                            <tr> 
                              <td width="90" align="center"><a href="http://www.microsoft.com/windows/windowsmedia/download/default.asp?DispLang=fr" target="_blank" onMouseOver="Bulle('Télécharger le lecteur &quot;<b>Windows Media Player</b> série 9&quot; (Gratuit, 10Mo)');" onMouseOut="nd();"><img src="images_videos/wmp3b.gif" width="82" height="50" border="0"></a></td>
                              <td width="90" align="center"><a href="http://forms.real.com/netzip/intl/intl_getrde601.html?lang=fr&h=207.188.7.150&f=windows/mrkt/RIR09D/RealOnePlayerV2GOLD_fr.exe&p=RealOne%2BPlayer&oem=rd_fr&src=030324_intl_radiopasschoice_fr_fr,030324radiopass_choice_dl&tagtype=ie&type=rd_fr" target="_blank" onMouseOver="Bulle('Télécharger le lecteur &quot;<b>Real One Player</b>&quot; (Version gratuite ou payante, 8Mo)');" onMouseOut="nd();"><img src="images_videos/real3b.gif" width="82" height="50" border="0"></a></td>
                            </tr>
                          </table></td>
                      </tr>
                      <tr> 
                        <td width="1"><script language="JavaScript">
<!--
if (PlayerWmp == "oui" && CPlayer != "PlayerReal") {
document.write("<input type='radio' name='FPlayer' value='PlayerWmp' checked>");
} 
else if (PlayerWmp == "oui" && CPlayer != "PlayerWmp") {
document.write("<input type='radio' name='FPlayer' value='PlayerWmp'>");
}
else { document.write("<input type='radio' name='FPlayer' value='PlayerWmp' disabled>"); }
-->
</script></td>
                        <td nowrap class="textpetit2"><b>Windows Media Player</b></td>
                      </tr>
                    </table></td>
                </tr>
                <tr> 
                  <td><img src="images_videos/bar2.gif" width="100%" height="6"></td>
                </tr>
                <tr> 
                  <td height="40" align="center" background="images_videos/fd.gif"><input type="hidden" name="videosId" value="<?php echo $videosId; ?>"><input type="hidden" name="emissionId" value="<?php echo $emissionId; ?>">
<script language="JavaScript" >
<!--
if (PlayerReal!="oui" && PlayerWmp!="oui") {
document.write('<input name="Submit" type="submit" class="borNoir" value="Valider les param&egrave;tres"  title="Vous devez installer au moins un lecteur vidéo" disabled>');
}
else {
document.write('<input name="Submit" type="submit" class="borNoir" value="Valider les param&egrave;tres">');
}
//-->
</script>					
</td>
                </tr>
              </table></td>
          </tr>
        </form>
      </table><script language="JavaScript1.1" >
<!--
hsh = new Date();
hsd = document;
//hsr = hsd.referrer.replace(/[<>]/g, ''); //NOFRAME
hsr = parent.document.referrer.replace(/[<>]/g, ''); //FRAME
hsi = '<img width="1" height="1" src="http://logi6.xiti.com/hit.xiti?s=136376';
hsi += '&p=';
hsi += '&hl=' + hsh.getHours() + 'x' + hsh.getMinutes() + 'x' + hsh.getSeconds();
if(parseFloat(navigator.appVersion)>=4)
{Xiti_s=screen;hsi += '&r=' + Xiti_s.width + 'x' + Xiti_s.height + 'x' + Xiti_s.pixelDepth + 'x' + Xiti_s.colorDepth;}
hsd.writeln(hsi + '&ref=' + hsr.replace(/&/g, '$') + '"><\!--');
//-->
</script><noscript><img width="1" height="1" src="http://logi6.xiti.com/hit.xiti?s=136376&p=&"></noscript></td>
	</tr>
</table>
</body>
</html>